// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         {children}
//       </body>
//     </html>
//   );
// }



import './globals.css';
import { Inter } from 'next/font/google';
import { Metadata } from 'next';
import NextAuthProvider from '@/providers/NextAuth';
import Header from './components/Header';
import Footer from './components/Footer';
import { ToastProvider } from './context/ToastContext';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'とくたびログ',
	description: 'あなたの特別な旅行の思い出を記録しましょう',
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="ja">
			<head>
				<link
					rel="stylesheet"
					href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css"
					crossOrigin="anonymous"
				/>
			</head>
			<body className={inter.className}>
				<NextAuthProvider>
					<ToastProvider>
						<div className="min-h-screen flex flex-col">
							<Header />
							<main className="pt-16 flex-grow">
								{children}
							</main>
							<Footer />
						</div>
					</ToastProvider>
				</NextAuthProvider>
			</body>
		</html>
	);
}
